[package]
name = "oregon-storage"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[features]
default = []
test-hooks = []

[dependencies]
oregon-consensus = { path = "../oregon-consensus" }
oregon-primitives = { path = "../oregon-primitives" }
oregon-utxo = { path = "../oregon-utxo" }
rocksdb = { version = "=0.24.0", default-features = false, features = ["lz4", "bindgen-runtime"] }
thiserror = "2"
